CREATE TABLE Parks(
   parkkey    VARCHAR(5) NOT NULL PRIMARY KEY
  ,parkname   VARCHAR(38) NOT NULL
  ,parkalias  VARCHAR(74)
  ,city       VARCHAR(17) NOT NULL
  ,state      VARCHAR(15)
  ,country    VARCHAR(2) NOT NULL
);
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('ALB01','Riverside Park',NULL,'Albany','NY','US');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('ALT01','Columbia Park',NULL,'Altoona','PA','US');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('ANA01','Angel Stadium of Anaheim','Edison Field; Anaheim Stadium','Anaheim','CA','US');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('ARL01','Arlington Stadium',NULL,'Arlington','TX','US');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('ARL02','Rangers Ballpark in Arlington','The Ballpark in Arlington; Ameriquest Field','Arlington','TX','US');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('ATL01','Atlanta-Fulton County Stadium',NULL,'Atlanta','GA','US');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('ATL02','Turner Field',NULL,'Atlanta','GA','US');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('BAL01','Madison Avenue Grounds',NULL,'Baltimore','MD','US');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('BAL02','Newington Park',NULL,'Baltimore','MD','US');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('BAL03','Oriole Park I',NULL,'Baltimore','MD','US');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('BAL04','Belair Lot',NULL,'Baltimore','MD','US');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('BAL05','Monumental Park',NULL,'Baltimore','MD','US');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('BAL06','Oriole Park II',NULL,'Baltimore','MD','US');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('BAL07','Oriole Park III',NULL,'Baltimore','MD','US');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('BAL09','Oriole Park IV','American League Park','Baltimore','MD','US');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('BAL10','Terrapin Park','Oriole Park V','Baltimore','MD','US');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('BAL11','Memorial Stadium',NULL,'Baltimore','MD','US');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('BAL12','Oriole Park at Camden Yards',NULL,'Baltimore','MD','US');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('BOS01','South End Grounds I','Walpole Street Grounds','Boston','MA','US');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('BOS02','Dartmouth Grounds','Union Park','Boston','MA','US');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('BOS03','South End Grounds II',NULL,'Boston','MA','US');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('BOS04','Congress Street Grounds',NULL,'Boston','MA','US');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('BOS05','South End Grounds III',NULL,'Boston','MA','US');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('BOS06','Huntington Avenue Baseball Grounds',NULL,'Boston','MA','US');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('BOS07','Fenway Park',NULL,'Boston','MA','US');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('BOS08','Braves Field','Bee Hive','Boston','MA','US');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('BUF01','Riverside Grounds',NULL,'Buffalo','NY','US');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('BUF02','Olympic Park I',NULL,'Buffalo','NY','US');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('BUF03','Olympic Park II',NULL,'Buffalo','NY','US');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('BUF04','International Fair Association Grounds','Federal League Park','Buffalo','NY','US');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('CAN01','Mahaffey Park','Pastime Park','Canton','OH','US');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('CAN02','Pastime Park',NULL,'Canton','OH','US');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('CHI01','Lake Front Park I','Union Base-ball Grounds','Chicago','IL','US');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('CHI02','23rd Street Park',NULL,'Chicago','IL','US');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('CHI03','Lake Front Park II',NULL,'Chicago','IL','US');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('CHI04','Lake Front Park III',NULL,'Chicago','IL','US');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('CHI05','South Side Park I','Cricket Club Grounds; Union Grounds','Chicago','IL','US');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('CHI06','West Side Park',NULL,'Chicago','IL','US');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('CHI07','South Side Park II',NULL,'Chicago','IL','US');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('CHI08','West Side Grounds',NULL,'Chicago','IL','US');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('CHI09','South Side Park III',NULL,'Chicago','IL','US');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('CHI10','Comiskey Park I','White Sox Park','Chicago','IL','US');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('CHI11','Wrigley Field','Weeghman Park; Cubs Park','Chicago','IL','US');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('CHI12','U.S. Cellular Field','White Sox Park; Comiskey Park II','Chicago','IL','US');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('CIN01','Lincoln Park Grounds','Union Cricket Club Grounds','Cincinnati','OH','US');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('CIN02','Avenue Grounds',NULL,'Cincinnati','OH','US');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('CIN03','Bank Street Grounds',NULL,'Cincinnati','OH','US');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('CIN04','League Park I',NULL,'Cincinnati','OH','US');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('CIN05','League Park II',NULL,'Cincinnati','OH','US');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('CIN06','Palace of the Fans','League Park III','Cincinnati','OH','US');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('CIN07','Crosley Field','Redland Field','Cincinnati','OH','US');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('CIN08','Cinergy Field','Riverfront Stadium','Cincinnati','OH','US');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('CIN09','Great American Ballpark',NULL,'Cincinnati','OH','US');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('CLE01','National Association Grounds',NULL,'Cleveland','OH','US');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('CLE02','League Park I','Kennard Street Park','Cleveland','OH','US');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('CLE03','League Park II','American Association Park','Cleveland','OH','US');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('CLE04','Brotherhood Park','Players League Park','Cleveland','OH','US');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('CLE05','League Park III','National League Park III','Cleveland','OH','US');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('CLE06','League Park IV','Dunn Field','Cleveland','OH','US');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('CLE07','Cleveland Stadium','Municipal Stadium','Cleveland','OH','US');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('CLE08','Progressive Field','Jacobs Field','Cleveland','OH','US');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('CLE09','Cedar Avenue Driving Park',NULL,'Cleveland','OH','US');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('CLL01','Euclid Beach Park',NULL,'Collinwood','OH','US');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('COL01','Recreation Park I',NULL,'Columbus','OH','US');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('COL02','Recreation Park II',NULL,'Columbus','OH','US');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('COL03','Neil Park I',NULL,'Columbus','OH','US');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('COL04','Neil Park II',NULL,'Columbus','OH','US');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('COV01','Star Baseball Park',NULL,'Covington','KY','US');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('DAY01','Fairview Park',NULL,'Dayton','OH','US');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('DEN01','Mile High Stadium',NULL,'Denver','CO','US');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('DEN02','Coors Field',NULL,'Denver','CO','US');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('DET01','Recreation Park',NULL,'Detroit','MI','US');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('DET02','Bennett Park',NULL,'Detroit','MI','US');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('DET03','Burns Park','West End Park','Detroit','MI','US');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('DET04','Tiger Stadium','Navin Field; Briggs Stadium','Detroit','MI','US');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('DET05','Comerica Park',NULL,'Detroit','MI','US');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('DOV01','Fairview Park Fair Grounds',NULL,'Dover','DE','US');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('ELM01','Maple Avenue Driving Park',NULL,'Elmira','NY','US');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('FOR01','Grand Duchess','Hamilton Field','Fort Wayne','IN','US');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('FOR02','Swinney Park',NULL,'Fort Wayne','IN','US');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('FOR03','Jailhouse Flats',NULL,'Fort Wayne','IN','US');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('GEA01','Geauga Lake Grounds',NULL,'Geauga Lake','OH','US');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('GLO01','Gloucester Point Grounds',NULL,'Gloucester City','NJ','US');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('GRA01','Ramona Park',NULL,'Grand Rapids','MI','US');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('HAR01','Harrison Field',NULL,'Harrison','NJ','US');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('HON01','Aloha Stadium',NULL,'Honolulu','HI','US');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('HOU01','Colt Stadium',NULL,'Houston','TX','US');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('HOU02','Astrodome',NULL,'Houston','TX','US');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('HOU03','Minute Maid Park','Enron Field; Astros Field','Houston','TX','US');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('HRT01','Hartford Ball Club Grounds',NULL,'Hartford','CT','US');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('HRT02','Hartford Trotting Park',NULL,'Hartford','CT','US');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('IND01','South Street Park',NULL,'Indianapolis','IN','US');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('IND02','Seventh Street Park I',NULL,'Indianapolis','IN','US');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('IND03','Bruce Grounds',NULL,'Indianapolis','IN','US');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('IND04','Seventh Street Park II',NULL,'Indianapolis','IN','US');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('IND05','Seventh Street Park III',NULL,'Indianapolis','IN','US');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('IND06','Indianapolis Park',NULL,'Indianapolis','IN','US');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('IND07','Federal League Park','Washington Park','Indianapolis','IN','US');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('IRO01','Windsor Beach',NULL,'Irondequoit','NY','US');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('JER01','Oakland Park',NULL,'Jersey City','NJ','US');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('JER02','Roosevelt Stadium',NULL,'Jersey City','NJ','US');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('KAN01','Athletic Park',NULL,'Kansas City','MO','US');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('KAN02','Association Park',NULL,'Kansas City','MO','US');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('KAN03','Exposition Park',NULL,'Kansas City','MO','US');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('KAN04','Gordon and Koppel Field',NULL,'Kansas City','MO','US');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('KAN05','Municipal Stadium',NULL,'Kansas City','MO','US');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('KAN06','Kauffman Stadium','Royals Stadium','Kansas City','MO','US');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('KEO01','Perry Park','Walte''s Pasture','Keokuk','IA','US');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('LAS01','Cashman Field',NULL,'Las Vegas','NV','US');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('LBV01','The Ballpark at Disney''s Wide World',NULL,'Lake Buena Vista','FL','US');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('LOS01','Los Angeles Memorial Coliseum',NULL,'Los Angeles','CA','US');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('LOS02','Wrigley Field',NULL,'Los Angeles','CA','US');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('LOS03','Dodger Stadium','Chavez Ravine','Los Angeles','CA','US');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('LOU01','Louisville Baseball Park',NULL,'Louisville','KY','US');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('LOU02','Eclipse Park I',NULL,'Louisville','KY','US');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('LOU03','Eclipse Park II',NULL,'Louisville','KY','US');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('LOU04','Eclipse Park III',NULL,'Louisville','KY','US');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('LUD01','Ludlow Baseball Park',NULL,'Ludlow','KY','US');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('MAS01','Long Island Grounds',NULL,'Maspeth','NY','US');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('MIA01','Sun Life Stadium','Joe Robbie Stadium; Pro Player Stadium; Dolphin Stadium; LandShark Stadium','Miami','FL','US');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('MIA02','Marlins Park',NULL,'Miami','FL','US');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('MID01','Mansfield Club Grounds',NULL,'Middletown','CT','US');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('MIL01','Milwaukee Base-Ball Grounds',NULL,'Milwaukee','WI','US');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('MIL02','Wright Street Grounds',NULL,'Milwaukee','WI','US');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('MIL03','Athletic Park',NULL,'Milwaukee','WI','US');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('MIL04','Lloyd Street Grounds',NULL,'Milwaukee','WI','US');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('MIL05','County Stadium',NULL,'Milwaukee','WI','US');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('MIL06','Miller Park',NULL,'Milwaukee','WI','US');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('MIN01','Athletic Park',NULL,'Minneapolis','MN','US');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('MIN02','Metropolitan Stadium',NULL,'Bloomington','MN','US');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('MIN03','Hubert H. Humphrey Metrodome',NULL,'Minneapolis','MN','US');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('MIN04','Target Field',NULL,'Minneapolis','MN','US');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('MNT01','Estadio Monterrey',NULL,'Monterrey','Nuevo Leon','MX');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('MON01','Parc Jarry','Jarry Park','Montreal','QC','CA');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('MON02','Stade Olympique','Olympic Stadium','Montreal','QC','CA');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('NEW01','Howard Avenue Grounds','Brewster Park','New Haven','CT','US');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('NEW02','Hamilton Park',NULL,'New Haven','CT','US');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('NEW03','Beyerle''s Park','Forest City Park','Newburgh Township','OH','US');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('NWK01','Wiedenmeyer''s Park',NULL,'Newark','NJ','US');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('NYC01','Union Grounds',NULL,'Brooklyn','NY','US');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('NYC02','Capitoline Grounds',NULL,'Brooklyn','NY','US');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('NYC03','Polo Grounds I (Southeast Diamond)',NULL,'New York','NY','US');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('NYC04','Polo Grounds II (Southwest Diamond)',NULL,'New York','NY','US');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('NYC05','Washington Park I',NULL,'Brooklyn','NY','US');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('NYC06','Metropolitan Park',NULL,'New York','NY','US');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('NYC07','Grauer''s Ridgewood Park','Ridgewood Park I','Queens','NY','US');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('NYC08','Washington Park II',NULL,'Brooklyn','NY','US');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('NYC09','Polo Grounds III',NULL,'New York','NY','US');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('NYC10','Polo Grounds IV',NULL,'New York','NY','US');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('NYC11','Eastern Park',NULL,'Brooklyn','NY','US');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('NYC12','Washington Park III',NULL,'Brooklyn','NY','US');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('NYC13','Hilltop Park',NULL,'New York','NY','US');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('NYC14','Polo Grounds V',NULL,'New York','NY','US');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('NYC15','Ebbets Field',NULL,'Brooklyn','NY','US');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('NYC16','Yankee Stadium I',NULL,'New York','NY','US');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('NYC17','Shea Stadium','William A. Shea Stadium','New York','NY','US');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('NYC18','Wallace''s Ridgewood Park','Ridgewood Park II','Queens','NY','US');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('NYC19','Washington Park IV',NULL,'Brooklyn','NY','US');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('NYC20','Citi Field',NULL,'New York','NY','US');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('NYC21','Yankee Stadium II',NULL,'New York','NY','US');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('OAK01','Oakland-Alameda County Coliseum','Network Associates Coliseum','Oakland','CA','US');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('PEN01','East End Park','Pendleton Park','Cincinnati','OH','US');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('PHI01','Jefferson Street Grounds','Athletics Park','Philadelphia','PA','US');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('PHI02','Centennial Park',NULL,'Philadelphia','PA','US');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('PHI03','Oakdale Park',NULL,'Philadelphia','PA','US');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('PHI04','Recreation Park',NULL,'Philadelphia','PA','US');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('PHI05','Keystone Park',NULL,'Philadelphia','PA','US');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('PHI06','Huntingdon Grounds I',NULL,'Philadelphia','PA','US');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('PHI07','Forepaugh Park',NULL,'Philadelphia','PA','US');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('PHI08','University of Penn. Athletic Field',NULL,'Philadelphia','PA','US');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('PHI09','Baker Bowl',NULL,'Philadelphia','PA','US');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('PHI10','Columbia Park',NULL,'Philadelphia','PA','US');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('PHI11','Shibe Park','Connie Mack Stadium','Philadelphia','PA','US');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('PHI12','Veterans Stadium',NULL,'Philadelphia','PA','US');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('PHI13','Citizens Bank Park',NULL,'Philadelphia','PA','US');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('PHI14','Huntingdon Grounds II',NULL,'Philadelphia','PA','US');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('PHO01','Chase Field','Bank One Ballpark','Phoenix','AZ','US');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('PIT01','Union Park',NULL,'Pittsburgh','PA','US');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('PIT02','Exposition Park I','Lower Field','Pittsburgh','PA','US');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('PIT03','Exposition Park II','Upper Field','Pittsburgh','PA','US');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('PIT04','Recreation Park',NULL,'Pittsburgh','PA','US');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('PIT05','Exposition Park III',NULL,'Pittsburgh','PA','US');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('PIT06','Forbes Field',NULL,'Pittsburgh','PA','US');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('PIT07','Three Rivers Stadium',NULL,'Pittsburgh','PA','US');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('PIT08','PNC Park',NULL,'Pittsburgh','PA','US');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('PRO01','Adelaide Avenue Grounds',NULL,'Providence','RI','US');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('PRO02','Messer Street Grounds',NULL,'Providence','RI','US');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('RCK01','Agricultural Society Fair Grounds',NULL,'Rockford','IL','US');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('RIC01','Richmond Fair Grounds',NULL,'Richmond','VA','US');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('RIC02','Allens Pasture',NULL,'Richmond','VA','US');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('ROC01','Culver Field I',NULL,'Rochester','NY','US');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('ROC02','Culver Field II',NULL,'Rochester','NY','US');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('ROC03','Ontario Beach Grounds',NULL,'Rochester','NY','US');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('SAI01','St. George Cricket Grounds',NULL,'New York','NY','US');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('SAN01','Qualcomm Stadium','San Diego/Jack Murphy Stadium','San Diego','CA','US');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('SAN02','PETCO Park',NULL,'San Diego','CA','US');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('SEA01','Sick''s Stadium',NULL,'Seattle','WA','US');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('SEA02','Kingdome',NULL,'Seattle','WA','US');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('SEA03','Safeco Field',NULL,'Seattle','WA','US');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('SFO01','Seals Stadium',NULL,'San Francisco','CA','US');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('SFO02','Candlestick Park','3Com Park','San Francisco','CA','US');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('SFO03','AT&T Park','Pacific Bell Park; SBC Park','San Francisco','CA','US');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('SJU01','Estadio Hiram Bithorn',NULL,'San Juan',NULL,'PR');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('SPR01','Hampden Park Race Track','Springfield Track','Springfield','MA','US');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('STL01','Red Stockings Base Ball Park',NULL,'St. Louis','MO','US');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('STL02','Grand Avenue Park',NULL,'St. Louis','MO','US');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('STL03','Sportsman''s Park I',NULL,'St. Louis','MO','US');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('STL04','Union Grounds',NULL,'St. Louis','MO','US');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('STL05','Robison Field',NULL,'St. Louis','MO','US');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('STL06','Sportsman''s Park II',NULL,'St. Louis','MO','US');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('STL07','Sportsman''s Park III','Busch Stadium I','St. Louis','MO','US');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('STL08','Handlan''s Park','Federal League Park','St. Louis','MO','US');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('STL09','Busch Stadium II',NULL,'St. Louis','MO','US');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('STL10','Busch Stadium III',NULL,'St. Louis','MO','US');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('STP01','Tropicana Field',NULL,'St. Petersburg','FL','US');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('SYD01','Sydney Cricket Ground',NULL,'Sydney','New South Wales','AU');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('SYR01','Star Park I','Newell Park','Syracuse','NY','US');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('SYR02','Star Park II',NULL,'Syracuse','NY','US');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('SYR03','Iron Pier',NULL,'Syracuse','NY','US');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('THR01','Three Rivers Park',NULL,'Three Rivers','NY','US');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('TOK01','Tokyo Dome',NULL,'Tokyo','Tokyo','JP');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('TOL01','League Park',NULL,'Toledo','OH','US');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('TOL02','Tri-State Fair Grounds',NULL,'Toledo','OH','US');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('TOL03','Speranza Park',NULL,'Toledo','OH','US');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('TOL04','Armory Park',NULL,'Toledo','OH','US');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('TOR01','Exhibition Stadium',NULL,'Toronto','ON','CA');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('TOR02','Rogers Centre','Skydome','Toronto','ON','CA');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('TRO01','Haymakers'' Grounds',NULL,'Troy','NY','US');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('TRO02','Putnam Grounds',NULL,'Troy','NY','US');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('WAR01','Rocky Point Park',NULL,'Warwick','RI','US');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('WAS01','Olympic Grounds',NULL,'Washington','DC','US');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('WAS02','National Grounds',NULL,'Washington','DC','US');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('WAS03','Capitol Grounds',NULL,'Washington','DC','US');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('WAS04','Athletic Park',NULL,'Washington','DC','US');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('WAS05','Swampoodle Grounds',NULL,'Washington','DC','US');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('WAS06','Boundary Field',NULL,'Washington','DC','US');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('WAS07','American League Park I',NULL,'Washington','DC','US');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('WAS08','American League Park II',NULL,'Washington','DC','US');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('WAS09','Griffith Stadium',NULL,'Washington','DC','US');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('WAS10','Robert F. Kennedy Stadium','D.C. Stadium','Washington','DC','US');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('WAS11','Nationals Park',NULL,'Washington','DC','US');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('WAT01','Troy Ball Club Grounds',NULL,'Watervliet','NY','US');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('WAV01','Waverly Fairgrounds',NULL,'Waverly','NJ','US');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('WEE01','Monitor Grounds',NULL,'Weehawken','NJ','US');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('WHE01','Island Grounds',NULL,'Wheeling','WV','US');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('WIL01','Union Street Park',NULL,'Wilmington','DE','US');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('WNY01','West New York Field Club Grounds',NULL,'West New York','NJ','US');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('WOR01','Agricultural County Fair Grounds I',NULL,'Worcester','MA','US');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('WOR02','Agricultural County Fair Grounds II',NULL,'Worcester','MA','US');
INSERT INTO Parks(parkkey,parkname,parkalias,city,state,country) VALUES ('WOR03','Worcester Driving Park Grounds',NULL,'Worcester','MA','US');
